vim.g.mapleader = ","
require("core.sets")
require("core.plugins")
require("core.map")
require("core.run")
require("core.spring")
require("core.commands")
require("core.newfile")
require("core.newdir")
require("core.quickfix_replace")
require("core.diagnostics")
require("core.dashboard")
require("plugins.markdown")
require("themes.cyberia")
