general {
    lock_cmd = $HOME/.local/bin/lockscreen
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# blocks after five minutes without interaction
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# switch off screen after thirty seconds 
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend screen after twenty minutes when on battery
listener {
    timeout = 1200
    on-timeout = systemctl suspend
    condition_cmd = test "$(cat /sys/class/power_supply/AC/online)" = 0
    condition_retry = 60
}
